// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIpblCzr3LyL6Fr4g3bpSy_AVFju96sQ',
    appId: '1:768923100415:android:fa2d8fc7ba39d4aaa558ca',
    messagingSenderId: '768923100415',
    projectId: 'goodmoodapp-13260',
    storageBucket: 'goodmoodapp-13260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHZ9DjghdyDnXtx4zj66VGteo440Uvhw',
    appId: '1:768923100415:ios:72562522448ad25da558ca',
    messagingSenderId: '768923100415',
    projectId: 'goodmoodapp-13260',
    storageBucket: 'goodmoodapp-13260.appspot.com',
    iosClientId: '768923100415-6m8jo396rna81htoc0283s7j67e96ske.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodMood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdHZ9DjghdyDnXtx4zj66VGteo440Uvhw',
    appId: '1:768923100415:ios:42e4cee9db9504a8a558ca',
    messagingSenderId: '768923100415',
    projectId: 'goodmoodapp-13260',
    storageBucket: 'goodmoodapp-13260.appspot.com',
    iosClientId: '768923100415-jvoae600ap4ilfgb7k65qujga10e2aio.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodMood.RunnerTests',
  );
}
